### ISSUE TITLE
T-minus 5 seconds...

### ISSUE THREAD

**Issue by gmglickman** [mykle1/MMM-Launch#3]
Fresh install, and all I get is "T- minus 5 seconds and counting." No header, nothing else.
Config:
`	{
	    module: 'MMM-Launch',
	    position: 'top_right',               // Best in left or right region
	    config: {
			showPix: "Yes",                 // No = No picture
			showAgency: "Yes",              // No = Launch Agency not shown
			showDescription: "Yes",          // Yes = full description of mission under picture
			useHeader: true,               // false if you don't want a header
			header: "MMM-Launch",    
			maxWidth: "300px"
	    }
	},
`
with or without comma after last config item.

Don't know why it's not loading. Startup sequence include these:
`Module helper loaded: MMM-Launch
Initializing new module helper ...

Connecting socket for: MMM-Launch
Starting node_helper for: MMM-Launch
`

**Comment by mykle1** [comment]
The API was deprecated and I did not know about it. Another user spotted it and issued a PR that I merged into the module. It should be working for you now. It does take a few moments to load so please wait a few seconds. Thanks for your interest
